#!/usr/bin/env python3
"""Conditional observables of one frozen two-slope ECT-completion background.

The dimensionless background is generated by the declared scalar--tensor
action and supplied initial state.  Each H0 value is an alternative disclosed
dimensional calibration of that same fixed orbit and state, not a replacement background;
it is a mere change of units only if all physical clocks, matter, Planck and
recombination scales are co-rescaled.  The growth and
sound-horizon layers are explicitly conditional approximations with their
extra metric, quasistatic, photon and recombination assumptions recorded in
the output.  Nothing in this script is a unique P1--P6 prediction.
"""

from __future__ import annotations

import csv
import json
import platform
from pathlib import Path

import numpy as np
import scipy
from scipy.integrate import quad, solve_ivp


HERE = Path(__file__).resolve().parent
OUT = (
    HERE.parents[1] / "data/cosmology_r103"
    if HERE.name == "cosmology" and HERE.parent.name == "scripts"
    else HERE.parent / "results"
)
JSON_OUT = OUT / "R103_TWO_SLOPE_CONDITIONAL_OBSERVABLES_v1.json"
CSV_OUT = OUT / "R103_TWO_SLOPE_CONDITIONAL_OBSERVABLES_v1.csv"
DENSE_OUT = OUT / "R103_TWO_SLOPE_BACKGROUND_DENSE_v1.csv"
DENSE_META_OUT = OUT / "R103_TWO_SLOPE_BACKGROUND_DENSE_METADATA_v1.json"

MPC_KM = 3.0856775814913673e19
JULIAN_YEAR_S = 31_557_600.0
GYR_S = 1.0e9 * JULIAN_YEAR_S
C_KM_S = 299_792.458

# Frozen near-GR two-slope completion, in F_*=H_*=1 units.
A = 0.01
C = 0.01
B = 0.03
KAPPA = 10.0
RHO_M0 = 0.9
RHO_R0 = 3.0e-4
V_MINUS = 0.82485
V_PLUS = 1.27485
N_INITIAL = -60.0

Z_GRID = (0.0, 0.5, 1.0, 2.0, 4.9, 7.0, 10.0, 14.32, 20.0)
H0_MATCHES = (67.4, 73.04)

# Illustrative standard photon/recombination layer.  These are inputs, not
# outputs of the scalar completion.
OMEGA_B_STD = 0.0493
OMEGA_GAMMA_STD = 5.45e-5
Z_DRAG_STD = 1059.94


def background_point(n: float, q: float, p: float) -> dict[str, float]:
    f = float(np.exp(A * q))
    f_q = A * f
    f_qq = A**2 * f
    kinetic = KAPPA * f
    kinetic_q = A * kinetic
    potential = V_MINUS * np.exp(C * q) + V_PLUS * np.exp(B * q)
    potential_q = C * V_MINUS * np.exp(C * q) + B * V_PLUS * np.exp(B * q)
    rho_m = RHO_M0 * np.exp(-3.0 * n)
    rho_r = RHO_R0 * np.exp(-4.0 * n)
    denominator = 3.0 * f + 3.0 * f_q * p - 0.5 * kinetic * p**2
    if denominator <= 0.0:
        raise FloatingPointError("non-positive Friedmann denominator")
    hubble = float(np.sqrt((rho_m + rho_r + potential) / denominator))
    friedmann_lhs = hubble**2 * denominator
    friedmann_rhs = rho_m + rho_r + potential
    constraint_signed = friedmann_lhs - friedmann_rhs
    constraint_scale = max(
        abs(friedmann_lhs), abs(friedmann_rhs), np.finfo(float).tiny
    )
    constraint_abs = abs(constraint_signed)
    constraint_rel = constraint_signed / constraint_scale
    q_dot = hubble * p
    rhs_ray = -(
        rho_m + 4.0 * rho_r / 3.0 + kinetic * q_dot**2
        + f_qq * q_dot**2 - hubble * f_q * q_dot
    )
    rhs_scalar = (
        -3.0 * kinetic * hubble * q_dot
        - 0.5 * kinetic_q * q_dot**2
        - potential_q + 6.0 * f_q * hubble**2
    )
    h_dot, q_ddot = np.linalg.solve(
        np.array([[2.0 * f, f_q], [-3.0 * f_q, kinetic]]),
        np.array([rhs_ray, rhs_scalar]),
    )
    p_prime = q_ddot / hubble**2 - p * h_dot / hubble**2
    return {
        "H": hubble,
        "Hprime_over_H": float(h_dot / hubble**2),
        "p_prime": float(p_prime),
        "F": f,
        "V": float(potential),
        "rho_m": float(rho_m),
        "rho_r": float(rho_r),
        "constraint_signed": float(constraint_signed),
        "constraint_abs": float(constraint_abs),
        "constraint_rel": float(constraint_rel),
        "constraint_scale": float(constraint_scale),
        "friedmann_denominator": float(denominator),
        "response_determinant": float(2.0 * f * kinetic + 3.0 * f_q**2),
    }


def background_rhs(n: float, state: np.ndarray) -> np.ndarray:
    q, p, elapsed = state
    del elapsed
    point = background_point(n, float(q), float(p))
    return np.array([p, point["p_prime"], 1.0 / point["H"]])


def integrate_background(method: str):
    sol = solve_ivp(
        background_rhs,
        (N_INITIAL, 0.0),
        np.array([0.0, 0.0, 0.0]),
        method=method,
        rtol=1.0e-11,
        atol=1.0e-13,
        max_step=0.02,
        dense_output=True,
    )
    if not sol.success:
        raise RuntimeError(f"{method} background failure: {sol.message}")
    return sol


def quad_n(fun, low: float, high: float) -> float:
    value, _ = quad(fun, low, high, epsabs=2.0e-11, epsrel=2.0e-11, limit=500)
    return float(value)


def main() -> None:
    dop = integrate_background("DOP853")
    rad = integrate_background("Radau")

    def state(n: float) -> tuple[float, float, float]:
        q, p, elapsed = dop.sol(n)
        return float(q), float(p), float(elapsed)

    q0, p0, elapsed0 = state(0.0)
    today = background_point(0.0, q0, p0)
    h0_model = today["H"]
    f0 = today["F"]
    tau0 = h0_model * elapsed0
    q0_r, p0_r, elapsed0_r = map(float, rad.y[:, -1])
    h0_r = background_point(0.0, q0_r, p0_r)["H"]
    tau0_r = h0_r * elapsed0_r

    omega_m0 = RHO_M0 / (3.0 * f0 * h0_model**2)
    omega_r0 = RHO_R0 / (3.0 * f0 * h0_model**2)
    omega_l0 = 1.0 - omega_m0 - omega_r0

    def model_point(n: float) -> dict[str, float]:
        q, p, elapsed = state(n)
        point = background_point(n, q, p)
        point.update({"q": q, "p": p, "elapsed": elapsed})
        return point

    def e_ref(n: float) -> float:
        return float(np.sqrt(
            omega_r0 * np.exp(-4.0 * n)
            + omega_m0 * np.exp(-3.0 * n)
            + omega_l0
        ))

    def h0_over_h(n: float) -> float:
        return h0_model / model_point(n)["H"]

    def cs_over_c(n: float) -> float:
        one_plus_z = np.exp(-n)
        r_b = 3.0 * OMEGA_B_STD / (4.0 * OMEGA_GAMMA_STD * one_plus_z)
        return float(1.0 / np.sqrt(3.0 * (1.0 + r_b)))

    # Conditional quasistatic growth: Jordan matter metric, conserved dust,
    # no exchange/mixing source, negligible scale dependence and scalar mass,
    # with the massless scalar-tensor coupling factor normalized at N=0.
    n_growth = -np.log(101.0)

    def growth_rhs_model(n: float, y: np.ndarray) -> np.ndarray:
        point = model_point(n)
        omega_m_fixed = point["rho_m"] / (3.0 * f0 * point["H"]**2)
        mu_qs = f0 / point["F"]
        d, dp = y
        return np.array([
            dp,
            -(2.0 + point["Hprime_over_H"]) * dp
            + 1.5 * omega_m_fixed * mu_qs * d,
        ])

    def growth_rhs_ref(n: float, y: np.ndarray) -> np.ndarray:
        e = e_ref(n)
        hprime = -(
            4.0 * omega_r0 * np.exp(-4.0 * n)
            + 3.0 * omega_m0 * np.exp(-3.0 * n)
        ) / (2.0 * e**2)
        omega_m = omega_m0 * np.exp(-3.0 * n) / e**2
        d, dp = y
        return np.array([dp, -(2.0 + hprime) * dp + 1.5 * omega_m * d])

    growth_model = solve_ivp(
        growth_rhs_model, (n_growth, 0.0), np.array([1.0, 1.0]),
        method="DOP853", rtol=2.0e-11, atol=2.0e-13, max_step=0.01,
        dense_output=True,
    )
    growth_ref = solve_ivp(
        growth_rhs_ref, (n_growth, 0.0), np.array([1.0, 1.0]),
        method="DOP853", rtol=2.0e-11, atol=2.0e-13, max_step=0.01,
        dense_output=True,
    )
    if not growth_model.success or not growth_ref.success:
        raise RuntimeError("conditional growth integration failed")
    dm0 = float(growth_model.y[0, -1])
    dr0 = float(growth_ref.y[0, -1])

    rows: list[dict[str, float]] = []
    for z in Z_GRID:
        n = -np.log1p(z)
        point = model_point(n)
        e_model = point["H"] / h0_model
        eref = e_ref(n)
        hprime_ref = -(
            4.0 * omega_r0 * np.exp(-4.0 * n)
            + 3.0 * omega_m0 * np.exp(-3.0 * n)
        ) / (2.0 * eref**2)
        age_tau = h0_model * point["elapsed"]
        lookback_tau = tau0 - age_tau
        chi = quad_n(lambda nn: np.exp(-nn) * h0_over_h(nn), n, 0.0)
        chi_ref = quad_n(lambda nn: np.exp(-nn) / e_ref(nn), n, 0.0)
        age_ref = quad_n(lambda nn: 1.0 / e_ref(nn), N_INITIAL, n)
        dm, dmp = map(float, growth_model.sol(max(n, n_growth)))
        dr, drp = map(float, growth_ref.sol(max(n, n_growth)))
        dm_norm = dm / dm0
        dr_norm = dr / dr0
        rows.append({
            "z": z,
            "E_two_slope": e_model,
            "E_reference": eref,
            "delta_E_percent": 100.0 * (e_model / eref - 1.0),
            "w_eff_two_slope": -1.0 - 2.0 * point["Hprime_over_H"] / 3.0,
            "w_eff_reference": -1.0 - 2.0 * hprime_ref / 3.0,
            "H0_t_two_slope": age_tau,
            "H0_t_reference": age_ref,
            "H0_lookback_two_slope": lookback_tau,
            "H0_chi_over_c_two_slope": chi,
            "H0_chi_over_c_reference": chi_ref,
            "delta_chi_percent": 100.0 * (chi / chi_ref - 1.0) if z else 0.0,
            "D_two_slope_normalized": dm_norm,
            "D_reference_normalized": dr_norm,
            "delta_D_percent": 100.0 * (dm_norm / dr_norm - 1.0),
            "f_two_slope": dmp / dm,
            "f_reference": drp / dr,
            "F_over_F0": point["F"] / f0,
        })

    n_drag = -np.log1p(Z_DRAG_STD)
    rs_model = quad_n(
        lambda nn: np.exp(-nn) * cs_over_c(nn) * h0_over_h(nn),
        N_INITIAL, n_drag,
    )
    rs_ref = quad_n(
        lambda nn: np.exp(-nn) * cs_over_c(nn) / e_ref(nn),
        N_INITIAL, n_drag,
    )

    unit_conversions = {}
    for h0 in H0_MATCHES:
        hubble_time_gyr = MPC_KM / h0 / GYR_S
        unit_conversions[f"H0_{h0:.2f}"] = {
            "H0_km_s_Mpc": h0,
            "age_today_Gyr": tau0 * hubble_time_gyr,
            "c_over_H0_Mpc": C_KM_S / h0,
            "r_s_conditional_Mpc": rs_model * C_KM_S / h0,
            "r_s_reference_same_inputs_Mpc": rs_ref * C_KM_S / h0,
            "jwst_cosmic_ages_Gyr": {
                f"z={row['z']:.2f}": row["H0_t_two_slope"] * hubble_time_gyr
                for row in rows if row["z"] in (4.9, 7.0, 10.0, 14.32, 20.0)
            },
        }

    # Galaxy-formation intervals used only as time-budget diagnostics.
    row_by_z = {row["z"]: row for row in rows}
    formation_intervals = []
    for z_obs, z_form in ((4.9, 10.0), (7.0, 14.32), (10.0, 20.0), (14.32, 20.0)):
        dt_tau = row_by_z[z_obs]["H0_t_two_slope"] - row_by_z[z_form]["H0_t_two_slope"]
        formation_intervals.append({
            "z_observed": z_obs,
            "z_formation": z_form,
            "H0_delta_t": dt_tau,
            "delta_t_Gyr_H0_67.4": dt_tau * MPC_KM / 67.4 / GYR_S,
            "delta_t_Gyr_H0_73.04": dt_tau * MPC_KM / 73.04 / GYR_S,
        })

    grid = np.linspace(N_INITIAL, 0.0, 3001)
    diagnostics = [model_point(float(n)) for n in grid]
    checks = {
        "background_DOP853_Radau_tau_agree_below_5e_minus_13": abs(tau0 - tau0_r) < 5.0e-13,
        "background_positive_F": min(row["F"] for row in diagnostics) > 0.0,
        "background_positive_H2": min(row["H"] for row in diagnostics) > 0.0,
        "background_positive_friedmann_denominator": min(row["friedmann_denominator"] for row in diagnostics) > 0.0,
        "background_positive_response_determinant": min(row["response_determinant"] for row in diagnostics) > 0.0,
        "background_max_abs_relative_Friedmann_residual_below_5e_minus_15": max(
            abs(row["constraint_rel"]) for row in diagnostics
        ) < 5.0e-15,
        "growth_solvers_success": growth_model.success and growth_ref.success,
        "sound_horizon_positive": rs_model > 0.0 and rs_ref > 0.0,
    }

    payload = {
        "date": "2026-07-18",
        "status": (
            "Level A background inside the supplied scalar-tensor action; "
            "Level C conditional observable estimates; not a unique ECT prediction"
        ),
        "runtime": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "scipy": scipy.__version__,
        },
        "action_inputs": {
            "a": A, "b": B, "c": C, "kappa": KAPPA,
            "rho_m0": RHO_M0, "rho_r0": RHO_R0,
            "V_minus": V_MINUS, "V_plus": V_PLUS,
            "N_initial": N_INITIAL,
        },
        "derived_today": {
            "q": q0, "dq_dN": p0, "F": f0,
            "H_in_reference_units": h0_model,
            "tau_2s_H2s0_Delta_t": tau0,
            "Omega_m0_reference_comparator": omega_m0,
            "Omega_r0_reference_comparator": omega_r0,
            "Omega_Lambda_reference_comparator": omega_l0,
        },
        "conditional_assumptions": {
            "distances": "Jordan photon metric equals the background metric; c_gamma=c; redshift 1+z=a^-1",
            "growth": (
                "conserved pressureless Jordan matter; quasistatic subhorizon limit; "
                "no exchange or mixing source; scale-independent massless scalar response "
                "normalized today, mu_QS=F0/F; no nonlinear/bias likelihood"
            ),
            "sound_horizon": {
                "physical_photon_metric": "same as background metric",
                "Omega_b": OMEGA_B_STD,
                "Omega_gamma": OMEGA_GAMMA_STD,
                "z_drag": Z_DRAG_STD,
                "recombination_status": "standard illustrative input, not derived from ECT",
            },
            "reference_comparator": (
                "flat radiation+matter+constant-source background using the same derived present "
                "dimensionless density fractions; this comparator is not inserted into the ECT solve"
            ),
        },
        "rows": rows,
        "formation_intervals": formation_intervals,
        "sound_horizon_dimensionless": {
            "H0_r_s_over_c_two_slope": rs_model,
            "H0_r_s_over_c_reference": rs_ref,
            "delta_percent": 100.0 * (rs_model / rs_ref - 1.0),
        },
        "unit_conversions": unit_conversions,
        "checks": checks,
        "all_checks_pass": all(checks.values()),
        "binding_caveat": (
            "the action coefficients, initial state, metric, photon/recombination layer and ordering event "
            "are supplied or matched inputs; H0 is the single dimensional calibration and the Planck "
            "normalization is an additional matched input; only the named conditional completion is tested"
        ),
    }

    OUT.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    with CSV_OUT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    dense_rows = []
    for n in grid:
        point = model_point(float(n))
        dense_rows.append({
            "N": float(n), "H": point["H"], "q": point["q"],
            "p": point["p"], "F": point["F"], "V": point["V"],
            "rho_m": point["rho_m"], "rho_r": point["rho_r"],
            "constraint_signed": point["constraint_signed"],
            "constraint_abs": point["constraint_abs"],
            "constraint_rel": point["constraint_rel"],
        })
    with DENSE_OUT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(dense_rows[0]))
        writer.writeheader()
        writer.writerows(dense_rows)
    dense_meta = {
        "schema": "ECT-R103-two-slope-dense-background-v1",
        "status": "conditional named two-slope action/state; not a universal P1--P6 history",
        "units": "F_*=H_*=1; N=ln(a); q dimensionless; p=dq/dN",
        "columns": {
            "N": "log scale factor", "H": "conditional Hubble rate in H_* units",
            "q": "two-slope scalar", "p": "dq/dN", "F": "exp(a q)",
            "V": "V_- exp(c q)+V_+ exp(b q)",
            "rho_m": "rho_m0 exp(-3N)", "rho_r": "rho_r0 exp(-4N)",
            "constraint_signed": "R_F=H^2(3F+3F_q p-Kp^2/2)-(rho_m+rho_r+V)",
            "constraint_abs": "|R_F|; absolute residual is scale dependent and is not the numerical acceptance metric",
            "constraint_rel": (
                "R_F/max(|H^2(3F+3F_q p-Kp^2/2)|,"
                "|rho_m+rho_r+V|,tiny); signed normalized Friedmann residual"
            ),
        },
        "grid": {"N_min": N_INITIAL, "N_max": 0.0, "points": len(dense_rows)},
        "solver": {
            "primary": "DOP853", "independent": "Radau",
            "rtol": 1.0e-11, "atol": 1.0e-13, "max_step": 0.02,
        },
        "constraint_gate": {
            "metric": "max(abs(constraint_rel)) on the published 3001-point grid",
            "threshold": 5.0e-15,
            "value": max(abs(row["constraint_rel"]) for row in dense_rows),
            "pass": max(abs(row["constraint_rel"]) for row in dense_rows) < 5.0e-15,
            "interpretation": (
                "large absolute residuals at very early N are floating-point "
                "cancellation between terms of order 1e100; the dimensionless "
                "relative residual is the meaningful numerical gate"
            ),
        },
        "calibration_guard": (
            "67.4 and 73.04 are two alternative dimensional calibrations of the same fixed orbit and state; "
            "they are not merely interchangeable unit rescalings unless every physical "
            "clock, matter, Planck and recombination scale is co-rescaled"
        ),
    }
    DENSE_META_OUT.write_text(json.dumps(dense_meta, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2, sort_keys=True))
    if not payload["all_checks_pass"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
