#!/usr/bin/env python3
"""Verify a supplied state and dimensional calibration for the R103 ECT age.

The dimensionless background history is generated by the declared
two-slope scalar--tensor completion.  The two H0 values below are alternative
dimensional calibrations of the same fixed orbit and supplied state; they do not replace
the model dynamics by LambdaCDM and are mere unit changes only if every
physical clock, matter, Planck and recombination scale is co-rescaled.  The
script also estimates the N<-20 radiation tail and tests the
finite-start initialization against the regular radiation branch evolved
at earlier cutoffs.
"""

from __future__ import annotations

import json
import platform
from pathlib import Path

import numpy as np
import scipy
from scipy.integrate import quad, solve_ivp


HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "data/cosmology_r103" / "R103_CONDITIONAL_ECT_AGE_MATCHING_RESULTS_v1.json"

# Unit definitions.  Mpc follows the IAU parsec conversion used in the
# original background audit; the year is the Julian year.
MPC_KM = 3.0856775814913673e19
JULIAN_YEAR_S = 31_557_600.0
GYR_S = 1.0e9 * JULIAN_YEAR_S

# Frozen near-GR two-slope completion.
A = 0.01
C = 0.01
B = 0.03
KAPPA = 10.0
RHO_M0 = 0.9
RHO_R0 = 3.0e-4
V_MINUS = 0.82485
V_PLUS = 1.27485


def background_point(n: float, q: float, p: float) -> tuple[float, float, float, float, float]:
    """Return H, p_N, Friedmann denominator, response determinant, and f."""
    f = np.exp(A * q)
    f_q = A * f
    f_qq = A**2 * f
    kinetic = KAPPA * f
    kinetic_q = A * kinetic
    potential = V_MINUS * np.exp(C * q) + V_PLUS * np.exp(B * q)
    potential_q = C * V_MINUS * np.exp(C * q) + B * V_PLUS * np.exp(B * q)
    rho_m = RHO_M0 * np.exp(-3.0 * n)
    rho_r = RHO_R0 * np.exp(-4.0 * n)

    friedmann_denominator = 3.0 * f + 3.0 * f_q * p - 0.5 * kinetic * p**2
    if friedmann_denominator <= 0.0:
        raise FloatingPointError("non-positive Friedmann response denominator")
    hubble = np.sqrt((rho_m + rho_r + potential) / friedmann_denominator)
    q_dot = hubble * p

    rhs_raychaudhuri = -(
        rho_m
        + 4.0 * rho_r / 3.0
        + kinetic * q_dot**2
        + f_qq * q_dot**2
        - hubble * f_q * q_dot
    )
    rhs_scalar = (
        -3.0 * kinetic * hubble * q_dot
        - 0.5 * kinetic_q * q_dot**2
        - potential_q
        + 6.0 * f_q * hubble**2
    )
    h_dot, q_ddot = np.linalg.solve(
        np.array([[2.0 * f, f_q], [-3.0 * f_q, kinetic]]),
        np.array([rhs_raychaudhuri, rhs_scalar]),
    )
    p_prime = q_ddot / hubble**2 - p * h_dot / hubble**2
    response_determinant = 2.0 * f * kinetic + 3.0 * f_q**2
    return hubble, p_prime, friedmann_denominator, response_determinant, f


def rhs(n: float, state: np.ndarray) -> np.ndarray:
    q, p, elapsed = state
    del elapsed
    hubble, p_prime, _, _, _ = background_point(n, q, p)
    return np.array([p, p_prime, 1.0 / hubble])


def integrate_from(n_initial: float, method: str) -> dict[str, float]:
    solution = solve_ivp(
        rhs,
        (n_initial, 0.0),
        np.array([0.0, 0.0, 0.0]),
        method=method,
        rtol=1.0e-11,
        atol=1.0e-13,
        max_step=0.02,
        dense_output=True,
    )
    if not solution.success:
        raise RuntimeError(f"{method} failed from N={n_initial}: {solution.message}")
    q_today, p_today, elapsed = solution.y[:, -1]
    hubble_today, _, _, _, _ = background_point(0.0, q_today, p_today)
    q_m20, p_m20, _ = solution.sol(-20.0) if n_initial < -20.0 else (0.0, 0.0, 0.0)
    return {
        "N_initial": float(n_initial),
        "q_at_N_minus_20": float(q_m20),
        "dq_dN_at_N_minus_20": float(p_m20),
        "q_today": float(q_today),
        "dq_dN_today": float(p_today),
        "H_today_in_reference_units": float(hubble_today),
        "H_today_times_elapsed": float(hubble_today * elapsed),
    }


def age_gyr(tau: float, h0_km_s_mpc: float) -> float:
    return tau * MPC_KM / h0_km_s_mpc / GYR_S


def main() -> None:
    runs: dict[str, dict[str, float]] = {}
    for n_initial in (-20.0, -30.0, -40.0, -60.0):
        runs[f"DOP853_N{int(n_initial)}"] = integrate_from(n_initial, "DOP853")
    runs["Radau_N-60"] = integrate_from(-60.0, "Radau")

    frozen = runs["DOP853_N-20"]
    regular = runs["DOP853_N-60"]
    regular_radau = runs["Radau_N-60"]
    tau_frozen = frozen["H_today_times_elapsed"]
    tau_regular = regular["H_today_times_elapsed"]

    # Exact radiation-asymptotic proper-time tail.  On the healthy branch
    # q_N=0 and f=f_i.  At N_i=-20,
    # H_r/H_* = sqrt(rho_r0/(3 f_i))*exp(-2 N_i).
    n_cut = -20.0
    f_cut = 1.0
    h0_over_hstar = frozen["H_today_in_reference_units"]
    tail_ref_radiation = (
        0.5 * np.sqrt(3.0 * f_cut / RHO_R0) * np.exp(2.0 * n_cut)
    )
    tail_tau_radiation = h0_over_hstar * tail_ref_radiation

    # Matter+radiation correction with q frozen is a tighter asymptotic
    # estimate at the cutoff; the scalar response enters only beyond this
    # approximation and is tested separately by the earlier-start evolution.
    a_cut = np.exp(n_cut)
    tail_ref_matter_radiation, tail_quad_error = quad(
        lambda scale: np.sqrt(3.0 * f_cut) * scale
        / np.sqrt(RHO_R0 + RHO_M0 * scale),
        0.0,
        a_cut,
        epsabs=1.0e-30,
        epsrel=1.0e-13,
    )
    tail_tau_matter_radiation = h0_over_hstar * tail_ref_matter_radiation

    h0_inputs = (67.4, 73.04)
    conversions = {}
    for h0 in h0_inputs:
        key = f"H0_{h0:.2f}"
        conversions[key] = {
            "H0_km_s_Mpc": h0,
            "Hubble_time_Gyr": MPC_KM / h0 / GYR_S,
            "frozen_N_minus_20_age_Gyr": age_gyr(tau_frozen, h0),
            "regular_branch_N_minus_60_age_Gyr": age_gyr(tau_regular, h0),
            "finite_start_systematic_years": age_gyr(tau_regular - tau_frozen, h0) * 1.0e9,
            "omitted_pure_radiation_tail_seconds": tail_tau_radiation * MPC_KM / h0,
            "omitted_matter_radiation_tail_seconds": tail_tau_matter_radiation * MPC_KM / h0,
        }

    checks = {
        "frozen_tau_reproduces_original": bool(abs(tau_frozen - 0.9636867786027802) < 5.0e-15),
        "regular_branch_cutoff_converged_N40_to_N60": bool(abs(
            runs["DOP853_N-40"]["H_today_times_elapsed"] - tau_regular
        ) < 5.0e-14),
        "regular_branch_cross_integrator": bool(abs(
            tau_regular - regular_radau["H_today_times_elapsed"]
        ) < 5.0e-13),
        "radiation_tail_below_3e_minus_16": bool(tail_tau_radiation < 3.0e-16),
        "matter_correction_below_3e_minus_6_relative": bool(abs(
            tail_tau_matter_radiation / tail_tau_radiation - 1.0
        ) < 3.0e-6),
        "finite_start_age_shift_below_5e_minus_11": bool(abs(tau_regular - tau_frozen) < 5.0e-11),
    }

    payload = {
        "date": "2026-07-18",
        "scope": (
            "conditional two-slope ECT-completion background with supplied state data; "
            "model-owned dimensionless dynamics with one disclosed H0 dimensional calibration"
        ),
        "status": (
            "Level A inside the declared scalar-tensor completion; not a unique ECT "
            "prediction and not a LambdaCDM background calculation"
        ),
        "runtime": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "scipy": scipy.__version__,
        },
        "inputs": {
            "a": A,
            "b": B,
            "c": C,
            "kappa": KAPPA,
            "rho_m0": RHO_M0,
            "rho_r0": RHO_R0,
            "V_minus": V_MINUS,
            "V_plus": V_PLUS,
            "H0_unit_matching_km_s_Mpc": list(h0_inputs),
        },
        "conditional_age_formula": "t0[Gyr] = tau * 977.7922216807891 / H0[km s^-1 Mpc^-1]",
        "tau_frozen_N_minus_20": tau_frozen,
        "tau_regular_branch_N_minus_60": tau_regular,
        "tau_regular_minus_frozen": tau_regular - tau_frozen,
        "omitted_tail": {
            "cutoff_N": n_cut,
            "H0_times_pure_radiation_tail": float(tail_tau_radiation),
            "H0_times_matter_radiation_tail": float(tail_tau_matter_radiation),
            "matter_radiation_relative_correction": float(
                tail_tau_matter_radiation / tail_tau_radiation - 1.0
            ),
            "quadrature_error_reference_units": float(tail_quad_error),
            "interpretation": (
                "the direct proper-time tail is about 90--97 seconds after H0 matching; "
                "the larger sub-year cutoff sensitivity comes from initializing q=q_N=0 "
                "at finite N rather than evolving the selected regular radiation branch from the past"
            ),
        },
        "unit_conversions": conversions,
        "cutoff_and_integrator_runs": runs,
        "checks": checks,
        "all_checks_pass": all(checks.values()),
        "binding_caveat": (
            "the dimensionless couplings, potential amplitudes, initial state and matter/photon "
            "metric are supplied or matched state data; H0 is the dimensional calibration, "
            "and the Planck normalization is an additional matched input; "
            "the microscopic completion and physical map remain Open"
        ),
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    OUT.write_text(text, encoding="utf-8")
    print(text, end="")
    if not payload["all_checks_pass"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
