#!/usr/bin/env python3
"""
Apply 15 GPT corrections (1-15) to ECT_preprint.tex.
(Correction 16 = bib-keys verification, done separately.)
"""
import re, sys
from pathlib import Path

LATEX = Path('/Users/chufelo/Documents/Physics/VDT/ECT/LaTex')
TEX = LATEX / 'ECT_preprint.tex'

text = TEX.read_text()
print(f"Loaded: {len(text)} chars, {text.count(chr(10))} lines")
print()

applied, failed = [], []

def safe_replace(t, old, new, label):
    if old not in t:
        failed.append((label, "anchor NOT FOUND"))
        return t
    cnt = t.count(old)
    if cnt != 1:
        failed.append((label, f"anchor count={cnt}"))
        return t
    nt = t.replace(old, new)
    applied.append(label)
    return nt

# -----------------------------------------------------------------
# PRAVKA 1: Caption fig:three_condensate_scales
# -----------------------------------------------------------------
pravka1_old = (
    r"""\caption{Illustrative schematic of the three condensate scale hierarchy
in ECT. \emph{Left:} running coupling $\lambda(\mu)$ as a function of
scale $\mu$ --- shown as a schematic estimate only; the actual RG
running in ECT has not yet been derived from first principles~(open;
OP-EW). \emph{Right:} the three characteristic scales $\phi_0\sim\bar{M}_{\rm Pl}$,
$v_2\sim246$\,GeV, and the galactic IR scale, separated by large
logarithms. The intermediate scale $v_2$ is fixed by electroweak
low-energy matching~\eqref{eq:v2_GF}, not derived from the condensate
action. The figure is a structural illustration of scale separation and possible
RG logic, not a quantitative ECT derivation of the intermediate scale.}"""
)

pravka1_new = (
    r"""\caption{Illustrative schematic of the three condensate scale hierarchy
in ECT. \emph{Left:} schematic locking/alignment coupling
$\eta_{\rm lock}(\mu)$ as a function of scale $\mu$. This is not the
bare scalar quartic $\lambda$ of the real-field potential, and its
actual beta-function has not yet been derived from ECT first principles
(open; OP-EW-scale). \emph{Right:} the three characteristic scales:
the UV condensate scale $\phi_0\sim\bar{M}_{\rm Pl}$, the matched
intermediate scale $v_2\sim246$\,GeV, and the galactic IR branch-variation
scale. The intermediate scale $v_2$ is fixed by electroweak low-energy
matching~\eqref{eq:v2_GF}, not derived from the condensate action.
The galactic scale is controlled by the IR/cosmological acceleration
scale $g^\dagger\sim cH_0/(2\pi)$ and is not generated by the same
RG flow as $v_2$. The figure is a structural illustration of scale
separation and possible non-polynomial scale-generation logic, not a
quantitative ECT derivation of the intermediate scale.}"""
)
text = safe_replace(text, pravka1_old, pravka1_new, "1: caption fig:three_condensate_scales")

# -----------------------------------------------------------------
# PRAVKA 2a: criticality problem → non-polynomial scale-generation problem
# -----------------------------------------------------------------
pravka2a_old = "We do not solve OP-EW here. We reduce the scale problem to a sharply\ndefined criticality problem."
pravka2a_new = "We do not solve OP-EW here. We reduce the scale problem to a sharply\ndefined non-polynomial scale-generation problem."
text = safe_replace(text, pravka2a_old, pravka2a_new, "2a: We reduce ... criticality problem")

# PRAVKA 2b
pravka2b_old = "an unnatural small ratio is converted\ninto a sharply defined order-one criticality problem."
pravka2b_new = "an unnatural small ratio is converted\ninto a sharply defined order-one scale-generation problem."
text = safe_replace(text, pravka2b_old, pravka2b_new, "2b: order-one criticality problem")

# -----------------------------------------------------------------
# PRAVKA 3: range 10^-3 to O(1)
# -----------------------------------------------------------------
pravka3_old = (
    "In all four scenarios the required UV input is ordinary --- between\n"
    "$\\mathcal{O}(10^{-3})$ and $\\mathcal{O}(1)$ --- not of order\n"
    "$10^{-16}$ or $10^{-32}$."
)
pravka3_new = (
    "In all four scenarios the required UV input is modest in logarithmic\n"
    "terms --- a dimensionless number of order $10^{-3}$--$10^{1}$ depending\n"
    "on the mechanism, never a direct coefficient of order $10^{-16}$ or\n"
    "$10^{-32}$."
)
text = safe_replace(text, pravka3_old, pravka3_new, "3: 10^-3 to 10^1 range")

# -----------------------------------------------------------------
# PRAVKA 4: Hopf fibration realisation paragraph
# -----------------------------------------------------------------
pravka4_old = (
    "\\paragraph{Hopf fibration realisation.}\n"
    "The coset $S^3$ admits the Hopf fibration\n"
    "$S^1\\hookrightarrow S^3\\to S^2$, with $S^2$ the orientation base\n"
    "and $S^1$ the locked phase fibre. This is structurally distinct from\n"
    "a trivial product $S^2\\times S^1$: motion along the phase circle is\n"
    "\\emph{coupled} to motion on the orientation sphere, with the coupling\n"
    "characterised by the Hopf invariant."
)
pravka4_new = (
    "\\paragraph{Hopf fibration realisation.}\n"
    "The coset $S^3$ admits the Hopf fibration\n"
    "$S^1\\hookrightarrow S^3\\to S^2$, with $S^2$ the orientation base\n"
    "and $S^1$ the locked phase fibre. This is structurally distinct from\n"
    "a trivial product $S^2\\times S^1$: the phase circle is non-trivially\n"
    "fibered over the orientation sphere. When field configurations are\n"
    "mapped into the $S^2$ base, their topological sectors can be classified\n"
    "by the Hopf invariant."
)
text = safe_replace(text, pravka4_old, pravka4_new, "4: Hopf fibration realisation")

# -----------------------------------------------------------------
# PRAVKA 5: kappa_n source reference
# -----------------------------------------------------------------
pravka5_old = (
    "$\\kappa_n$ specifically depends on closure of OP-Planck/OP-C$_n$\n"
    "through the NLO/induced route established in\n"
    "Appendix~\\ref{app:second_transition}."
)
pravka5_new = (
    "$\\kappa_n$ specifically depends on closure of OP-Planck/OP-C$_n$\n"
    "through the NLO/induced route discussed in\n"
    "Section~\\ref{sec:goldstone_soft_eft} and\n"
    "paragraph~\\ref{par:planck_scale}."
)
text = safe_replace(text, pravka5_old, pravka5_new, "5: kappa_n NLO route reference")

# -----------------------------------------------------------------
# PRAVKA 6: Hopfion subsection — static energy formulation
# -----------------------------------------------------------------
pravka6_old = (
    "If a finite-action 4D Euclidean topological configuration realised\n"
    "the Hopf-locking dynamics, its action would be bounded below in the\n"
    "Faddeev--Niemi\n"
    "model~\\cite{Faddeev1975,VakulenkoKapitanski1979,Niemi1997,BattyeSutcliffe1998}\n"
    "by a Vakulenko--Kapitanski-type inequality\n"
    "\\begin{equation}\n"
    "  S_{\\rm Hopfion}[Q_H]\\;\\geq\\;c\\,|Q_H|^{3/4},\n"
    "\\end{equation}\n"
    "where $Q_H\\in\\pi_3(S^2)=\\mathbb{Z}$ is the Hopf invariant and $c$ is\n"
    "a model-dependent numerical constant of order $(8\\pi^2)^{1/4}$."
)
pravka6_new = (
    "The closest developed mathematical template for the topological\n"
    "locking scenario is the Faddeev--Niemi\n"
    "model~\\cite{Faddeev1975,VakulenkoKapitanski1979,Niemi1997,BattyeSutcliffe1998}.\n"
    "In that setting, static three-dimensional Hopfion configurations obey a\n"
    "Vakulenko--Kapitanski-type lower bound on their finite static energy,\n"
    "\\begin{equation}\n"
    "  E_{\\rm Hopfion}[Q_H]\\;\\geq\\;c\\,|Q_H|^{3/4},\n"
    "\\end{equation}\n"
    "where $Q_H\\in\\pi_3(S^2)=\\mathbb{Z}$ is the Hopf invariant and $c$ is\n"
    "a model-dependent constant set by the stiffness and Skyrme-type\n"
    "coefficients of the effective model."
)
text = safe_replace(text, pravka6_old, pravka6_new, "6: Hopfion static energy")

# -----------------------------------------------------------------
# PRAVKA 7: BR1 derivation phrasing in second_transition
# -----------------------------------------------------------------
pravka7_old = (
    "a coherent phase sector with U(1) structure\n"
    "    (the winding variable $\\theta$; derived from BR1);"
)
pravka7_new = (
    "a coherent phase sector with compact U(1)-like structure in the\n"
    "    effective loop/phase description (the winding variable $\\theta$;\n"
    "    its role as an electroweak-locking participant is not derived from\n"
    "    P1--P6);"
)
text = safe_replace(text, pravka7_old, pravka7_new, "7: BR1 derivation softening")

# -----------------------------------------------------------------
# PRAVKA 8: b_0 lambda → b_a g_a^2
# -----------------------------------------------------------------
pravka8_old = (
    "For a one-loop running with coefficient $b_0$, this requires\n"
    "$b_0\\,\\lambda\\approx8\\pi^2/37\\approx2.1$, which is numerically\n"
    "plausible but does not constitute a derivation."
)
pravka8_new = (
    "For a schematic one-loop alignment running with coefficient $b_a$ and\n"
    "dimensionless locking coupling $g_a$, this would correspond to\n"
    "$b_a g_a^2(\\phi_0)\\approx8\\pi^2/37\\approx2.1$ in the strong-critical\n"
    "limit. This is numerically plausible but does not constitute a derivation."
)
text = safe_replace(text, pravka8_old, pravka8_new, "8: b_a g_a^2 wording")

# -----------------------------------------------------------------
# PRAVKA 9: second_transition_status item (i)
# -----------------------------------------------------------------
pravka9_old = (
    "\\item if a second effective ordering step $O(3)\\to O(2)$ is\n"
    "    admitted, then the generator counting is compatible with a\n"
    "    reduced weak-like symmetry-breaking pattern;"
)
pravka9_new = (
    "\\item if a second effective ordering step $O(3)\\to O(2)$ is\n"
    "    admitted, then it provides a reduced orientation-sector weak-like\n"
    "    analogue with two broken directions, but not the full electroweak\n"
    "    generator counting; the Hopf-fibered phase--orientation extension\n"
    "    of Appendix~\\ref{app:hopf_locking} is required for the candidate\n"
    "    three-broken-direction geometry;"
)
text = safe_replace(text, pravka9_old, pravka9_new, "9: status item (i) -- not full EW")

# -----------------------------------------------------------------
# PRAVKA 10: Old OP-EW description in Hierarchy/open list
# -----------------------------------------------------------------
pravka10_old = (
    "\\item[OP-EW (electroweak hierarchy).]\n"
    "    Why does a second condensate scale arise at $v_2\\ll \\phi_0$?\n"
    "    A structural candidate mechanism is described in\n"
    "    Appendix~\\ref{app:second_transition}; its realisation\n"
    "    within ECT remains open."
)
pravka10_new = (
    "\\item[OP-EW (electroweak hierarchy and locking programme).]\n"
    "    Why does a second condensate scale arise at $v_2\\ll\\phi_0$, and how\n"
    "    does the reduced orientation-sector transition extend to the full\n"
    "    electroweak-like generator structure? The old single OP-EW problem\n"
    "    is decomposed below into OP-EW-scale, OP-EW-locking, OP-EW-gauge,\n"
    "    OP-EW-naturalness, and OP-EW-matter. The reduced\n"
    "    $O(3)\\to O(2)$ candidate is described in\n"
    "    Appendix~\\ref{app:second_transition}; the Hopf-fibered\n"
    "    diagonal-locking upgrade is described in\n"
    "    Appendix~\\ref{app:hopf_locking}. Both remain structural\n"
    "    programmes, not derived results."
)
text = safe_replace(text, pravka10_old, pravka10_new, "10: OP-EW old single → layered")

# -----------------------------------------------------------------
# PRAVKA 11: Status summary table — 3 rows replaced by 6 rows
# -----------------------------------------------------------------
pravka11_old = (
    "Second transition $O(3)\\to O(2)$ as structural candidate & B & Requires phase--orientation coupling \\\\\n"
    "Gradient condensate from bare action & Open (OP-grad) & \\\\\n"
    "Phase--orientation coupling as dynamical driver & Open (OP-EW) & \\\\\n"
    "First-principles derivation of $v_2$ & Open (OP-EW) & \\\\\n"
)
pravka11_new = (
    "Reduced $O(3)\\to O(2)$ transition as orientation-sector analogue\n"
    "  & B/C & Two broken directions only; not full EW counting \\\\\n"
    "Gradient condensate from bare action & Open (OP-grad) & \\\\\n"
    "Hopf-fibered diagonal locking\n"
    "$\\mathrm{SU}(2)_{\\rm orient}\\times\\mathrm{U}(1)_\\theta\\to\n"
    "\\mathrm{U}(1)_{\\rm diag}$\n"
    "  & Candidate geometry & Three broken directions at pre-gauge/global level;\n"
    "  dynamics not derived (App.~\\ref{app:hopf_locking}) \\\\\n"
    "Origin of compact $\\mathrm{U}(1)_\\theta$ as EW-locking participant\n"
    "  & Open (OP-EW-locking.0) & Effective phase sector exists; EW role not derived \\\\\n"
    "First-principles derivation of $v_2=\\phi_0\\,e^{-\\mathcal{I}_{\\rm EW}}$\n"
    "  & Reduced (OP-EW-scale) & Non-polynomial scale-generation mechanism not derived \\\\\n"
    "Local chiral gauge completion, hypercharge, $g$, $g'$, Weinberg angle\n"
    "  & Open (OP-EW-gauge) & Not implied by Hopf geometry alone \\\\\n"
    "Radiative protection of $\\sigma_2$\n"
    "  & Open (OP-EW-naturalness) & Goldstone protection does not protect radial mode \\\\\n"
)
text = safe_replace(text, pravka11_old, pravka11_new, "11: status table 3rows->6rows (+OP-grad kept)")

# -----------------------------------------------------------------
# PRAVKA 12: Future directions item (ii)
# -----------------------------------------------------------------
pravka12_old = (
    "Origin of the electroweak scale $v_2$ (OP-EW).}\n"
    "The current formulation uses $v_2\\approx 246$\\,GeV as the\n"
    "secondary electroweak condensate scale required by phenomenological\n"
    "matching. A first-principles derivation of this scale, the dynamics\n"
    "of the corresponding second condensate transition, the ratio\n"
    "$v_2/\\phi_0\\sim 10^{-16}$, the gauge couplings $g,g'$, and the Yukawa\n"
    "hierarchy from condensate dynamics remains open. A structural\n"
    "candidate mechanism is described in\n"
    "Appendix~\\ref{app:second_transition}. If the hierarchy is to be\n"
    "closed through a running-coupling route, a full two-loop RG\n"
    "analysis with thresholds and matching would be required. Any such derivation, if\n"
    "achieved, would feed simultaneously into the electroweak boson\n"
    "mass scale, fermion mass matching, geometric-mean seesaw\n"
    "estimates, and fifth-force suppression factors, all of which\n"
    "currently use $v_2$ as an input (see the status paragraph in\n"
    "Section~\\ref{sec:ew_embedding})."
)
pravka12_new = (
    "Origin of the electroweak scale and locking structure (OP-EW).}\n"
    "The current formulation uses $v_2\\approx246$\\,GeV as the secondary\n"
    "electroweak scale required by low-energy matching. A first-principles\n"
    "derivation remains open at several logically distinct levels: the\n"
    "compact $\\mathrm{U}(1)_\\theta$ participant of the alignment sector\n"
    "(OP-EW-locking.0), the Hopf-fibered diagonal locking dynamics\n"
    "(OP-EW-locking.1), the non-polynomial scale-generation mechanism\n"
    "$v_2=\\phi_0\\,e^{-\\mathcal{I}_{\\rm EW}}$ with\n"
    "$\\mathcal{I}_{\\rm EW}\\approx36.8$ (OP-EW-scale), the local chiral\n"
    "$\\mathrm{SU}(2)_L\\times\\mathrm{U}(1)_Y$ gauge completion including\n"
    "$g$, $g'$ and the Weinberg angle (OP-EW-gauge), the protection of the\n"
    "secondary radial mode from additive $\\mathcal{O}(\\phi_0^2)$\n"
    "corrections (OP-EW-naturalness), and the chiral fermion/Yukawa sector\n"
    "(OP-EW-matter). The reduced $O(3)\\to O(2)$ analogue is described in\n"
    "Appendix~\\ref{app:second_transition}; the candidate Hopf-fibered\n"
    "phase--orientation geometry is described in\n"
    "Appendix~\\ref{app:hopf_locking}. Any complete derivation would feed\n"
    "simultaneously into the electroweak boson mass scale, fermion mass\n"
    "matching, geometric-mean seesaw estimates, and fifth-force suppression\n"
    "factors, all of which currently use $v_2$ as an input."
)
text = safe_replace(text, pravka12_old, pravka12_new, "12: Future directions (ii) layered")

# -----------------------------------------------------------------
# PRAVKA 13: Higgs section RGE quartic with y_t
# -----------------------------------------------------------------
pravka13_old = (
    "A dimensional-transmutation estimate via RGE of the condensate quartic coupling\n"
    "would in principle generate such a scale, but this requires external SM input\n"
    "(top-quark Yukawa $y_t\\approx0.95$) and remains Level~C~(Appendix~\\ref{app:second_transition})."
)
pravka13_new = (
    "The updated OP-EW-scale programme treats this hierarchy as a\n"
    "non-polynomial scale-generation problem,\n"
    "$v_2=\\phi_0\\,e^{-\\mathcal{I}_{\\rm EW}}$ with\n"
    "$\\mathcal{I}_{\\rm EW}\\approx36.8$\n"
    "(Section~\\ref{sec:three_scales}). Candidate mechanisms include\n"
    "alignment running, walking/near-conformal dynamics, Miransky/BKT\n"
    "scaling, and topological/Hopf-like routes\n"
    "(Appendix~\\ref{app:hopf_locking}). None is derived from P1--P6,\n"
    "and none by itself solves the radiative stability problem of\n"
    "the secondary radial mode."
)
text = safe_replace(text, pravka13_old, pravka13_new, "13: Higgs section RGE quartic")

# -----------------------------------------------------------------
# PRAVKA 14a: scaffold reference
# -----------------------------------------------------------------
pravka14a_old = "secondary-transition\nscaffold~(Appendix~\\ref{app:second_transition})."
pravka14a_new = "secondary-transition scaffold~(Appendix~\\ref{app:second_transition})\nand the candidate Hopf-fibered locking geometry\n(Appendix~\\ref{app:hopf_locking})."
text = safe_replace(text, pravka14a_old, pravka14a_new, "14a: scaffold ref + Hopf appendix")

# PRAVKA 14b
pravka14b_old = (
    "Its full first-principles realisation within ECT requires closing\n"
    "OP-EW~(Section~\\ref{sec:three_scales},\n"
    "Appendix~\\ref{app:second_transition})."
)
pravka14b_new = (
    "Its full first-principles realisation within ECT requires closing the\n"
    "layered OP-EW programme: OP-EW-scale, OP-EW-locking, OP-EW-gauge,\n"
    "OP-EW-naturalness, and OP-EW-matter\n"
    "(Section~\\ref{sec:three_scales},\n"
    "Appendices~\\ref{app:second_transition} and~\\ref{app:hopf_locking})."
)
text = safe_replace(text, pravka14b_old, pravka14b_new, "14b: layered closing OP-EW")

# -----------------------------------------------------------------
# PRAVKA 15: EW status table last row
# -----------------------------------------------------------------
pravka15_old = "Full EW sector derived from P1--P6\n  & Open (OP-EW) & \\\\"
pravka15_new = (
    "Full EW sector derived from P1--P6\n"
    "  & Open & Decomposes into OP-EW-scale, OP-EW-locking,\n"
    "    OP-EW-gauge, OP-EW-naturalness, and OP-EW-matter \\\\"
)
text = safe_replace(text, pravka15_old, pravka15_new, "15: EW status table last row")

# -----------------------------------------------------------------
print(f"\nApplied: {len(applied)} / 15+ targets")
for a in applied: print(f"  OK  {a}")
print(f"\nFailed: {len(failed)}")
for lbl, why in failed: print(f"  FAIL {lbl}: {why}")

if failed:
    print("\nABORTING: not writing file due to failed anchors.")
    sys.exit(1)

# Write back
TEX.write_text(text)
print(f"\nWritten {TEX.name}: {len(text)} chars, {text.count(chr(10))} lines")
